
version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 3333:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FRT@2023!
      POSTGRES_DB: postgres
  web:
    image: django:v1.0
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
