
version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 3333:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FRT@2023!
      POSTGRES_DB: postgres

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
  web:
    build: .
    ports:
      - 8000:8000
