version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "3333:5432"

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
